services:
  backend:
    image: khanh1205/mern-backend:1.0
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}

  frontend:
    image: khanh1205/mern-frontend:2.0
    ports:
      - "5173:4173"